version: '3'

services:
  ipfs:
    image: ipfs/go-ipfs
    ports:
      - "4001:4001" # ipfs swarm - expose if needed/wanted
      - "5001:5001" # ipfs api - expose if needed/wanted
      - "8080:8080" # ipfs gateway - expose if needed/wanted
    volumes:
      - ./ipfs:/data/ipfs
